---
title: 'Sequential Interaction Data for Educational Data Mining - A Review'
title-block-banner: false
description: 'Results and First Draft of Potential Publication'
author: 'Stefan Schmerda'
date: today
date-format: 'DD.MM.YYYY'
abstract: TODO
toc: true
toc-title: Table of Contents
toc-expand: true
toc-depth: 4
number-sections: true
number-depth: 4
format: 
    html:
        theme: default
        embed-resources: true
        page-layout: article
        smooth-scroll: true
        mermaid:
          theme: neutral
execute: 
  echo: false
  enable: true 
jupyter: python3
bibliography: references.bib
csl: elsevier-harvard.csl
---

<!-- import data -->
```{python}
import sys
sys.path.append('..')
import pickle
import pandas as pd

pd.options.display.max_colwidth = 100

with open('../pickled_objects/html_tables/csedm_2021_html_table.pickle', 'rb') as f:
  html_table = pickle.load(f)
```

## Introduction

TODO

### Research Questions

Data needs to be sequential interaction data.  
TODO: Rough overview of required dataset qualities.

::: {.callout-note appearance="minimal"}
## RQ1
Which datasets from the educational domain can be found that correspond to the requirements of representing the learning pathways of users? 
:::

TODO: write about the variability problem in MOOC learning paths

::: {.callout-note appearance="minimal"}
## RQ2
To which degree do learning pathways in the collected datasets differ by user?
:::

TODO: 

::: {.callout-note appearance="minimal"}
## RQ3
To what extend do different learning pathways effect the learning outcome? 
:::

## Definitions

### Learning Pathways
 
TODO: Short paragraph about learning pathway before the formal definition. (learning pathway -> attain learning goal)
The following states a formal definition of a learning pathway:

::: {#def-learning_path}
### Learning Pathway

A **learning pathway** consists of as a sequence of **learning resources** with a clear ordering. Let $LR$ be the sets of all learning resources and $I \subset \mathbb{N}$ the set of consecutive sequence index values, then a **learning pathway** $LP$ is defined as:

$$
LP:=\{lr_1,lr_2,...,lr_i\:|\: lr \in LR,\: i \in I\}
$$

A **learning pathway** $LP$ can be specific to a certain **topic** and **user**. Let $LR$, $T$, $U$ be the sets of all learning resources, topics and users respectively, then such a **learning pathway** can be written as:

$$
LP_{t, u}, where\: t\in T\: and\: u\in U
$$

:::

The learning pathways for a certain topic may vary by the user attempting to traverse the learning material of a topic. In @fig-learning_path
```{mermaid}
%%| label: fig-learning_path
%%| fig-cap: Examplatory Learning Paths for three users

flowchart LR
  direction LR
  START(Topic 1) -.- LR11((LR 1))
  START(Topic 1) -.- LR21((LR 1))
  START(Topic 1) -.- LR31((LR 2))

  subgraph Learning Path User 3
  LR31((LR 2)) --> LR32((LR 1))
  LR32((LR 1)) --> LR33((LR 3))
  LR33((LR 3)) --> LR34((LR 1))
  end

  subgraph Learning Path User 2
  LR21((LR 1)) --> LR22((LR 3))
  LR22((LR 3)) --> LR23((LR 2))
  end

  subgraph Learning Path User 1
  LR11((LR 1)) --> LR12((LR 2))
  LR12((LR 2)) --> LR13((LR 3))
  end
```

## Methodology

### Dataset requirements {#sec-dataset_requirements}

TODO

Datasets need to origin from the educational domain and conform to the requirements specified in @sec-interactions_fields and @sec-evaluation_fields in order to be selected for the analysis.

#### Interaction Fields {#sec-interactions_fields}

Therefore datasets which conform to the

| Timestamp | User | Topic | Learning Resource |
|:---------:|:----:|:-----:|:-----------------:|
| datetime  |  1   |   1   |         1         |
| datetime  |  ..  |  ..   |        ..         |
| datetime  |  n   |   n   |         n         |

: Requiered Fields {#tbl-req_fields}

#### Evaluation Fields {#sec-evaluation_fields}

TODO

#### Preprocessing Steps

TODO: NA Treatment, Merging ....

### Sequence Distance

TODO

The closeness between different learning paths is quantified via the application of Levenshtein Distance [@levenshtein1966].

### Clustering -

TODO

## Results
<!-- TODO rename repo such that it conforms to paper title -->

The following sections present the results of the paper.^[The code used for generating the cleaned datasets in @sec-results_datasets, for the sequence distance calculations in @sec-results_datasets_lp_var and for the clustering analysis in @sec-results_datasets_rel_lp_evaluation for each dataset respectively can be found in the [github repository](https://github.com/sschmerda/ddia_dataset_analysis) of the paper.]

### Datasets {#sec-results_datasets}

Datasets listed in @mihaescu2021 were surveyed and selected by conforming to the learning pathway requirements listed in @sec-dataset_requirements. The cleaned datasets can be downloaded from Zenodo^[Link to Zenodo repository]; the links to the raw data are listed on the paper's github repository^[https://github.com/sschmerda/ddia_dataset_analysis].

#### CSEDM 2019

#### CSEDM 2021

#### Educational Process Mining

#### KDD 2010

#### KDD 2015

#### Open University


#### Summary Statistics

```{python}
#| column: body-outset
#| label: summary_stats
#| fig-cap: 'Summary Statistics'

html_table.display_summary_statistics()
```

#### Available Fields

```{python}
#| column: body-outset
#| label: available_fields
#| fig-cap: 'Available Fields'

html_table.display_available_fields()
```

### Dataset Learning Pathway Variation {#sec-results_datasets_lp_var} 

### The Relationship between Learning Pathways and Evaluation Results {#sec-results_datasets_rel_lp_evaluation}

## Discussion

### Limitations

## Conclusion

TODO

## Links to Datasets {.appendix .unnumbered}

- [CSEDM 2019]()
- [CSEDM 2021]()


