name: DDIA
channels:
  - defaults
  - conda-forge
dependencies:
  - python-lsp-jsonrpc
  - black
  - asn1crypto
  - watchdog
  - wcwidth
  - pip
  - pkginfo
  - anyio
  - packaging
  - idna
  - backports.shutil_get_terminal_size
  - tbb
  - pyreadline
  - jupyterlab_pygments
  - mock
  - jupyter_core
  - python-lsp-server
  - pyodbc
  - lazy-object-proxy
  - libcurl
  - send2trash
  - prometheus_client
  - tblib
  - anaconda-project
  - tqdm
  - babel
  - unicodecsv
  - pluggy
  - pyzmq
  - snowballstemmer
  - threadpoolctl
  - openssl
  - anaconda-client
  - pyqt
  - powershell_shortcut
  - typing_extensions
  - munkres
  - zope
  - itsdangerous
  - jdcal
  - imagecodecs
  - pep8
  - console_shortcut
  - diff-match-patch
  - astropy
  - tk
  - jupyterlab_server
  - appdirs
  - html5lib
  - cached-property
  - bottleneck
  - msgpack-python
  - pandas
  - m2w64-gmp
  - paramiko
  - tornado
  - et_xmlfile
  - sortedcontainers
  - tbb4py
  - matplotlib-inline
  - spyder
  - locket
  - mkl-service
  - m2w64-gcc-libgfortran
  - path
  - inflection
  - nbformat
  - pynacl
  - scikit-image
  - xlsxwriter
  - whichcraft
  - cython
  - pyjwt
  - prompt_toolkit
  - rtree
  - zope.interface
  - jupyterlab_widgets
  - conda
  - jupyterlab
  - sip
  - decorator
  - backports.functools_lru_cache
  - pydocstyle
  - nbclassic
  - charls
  - wincertstore
  - jupyter_console
  - nbconvert
  - markupsafe
  - urllib3
  - pathlib2
  - setuptools
  - pywinpty
  - dal
  - ujson
  - qdarkstyle
  - lz4-c
  - parso
  - glob2
  - python-slugify
  - toolz
  - attrs
  - jinja2-time
  - libxslt
  - textdistance
  - qt
  - win_unicode_console
  - bitarray
  - sympy
  - nbclient
  - lzo
  - jpeg
  - llvmlite
  - terminado
  - unidecode
  - pickleshare
  - numexpr
  - sphinx
  - wheel
  - zict
  - dask-core
  - mkl
  - sortedcollections
  - widgetsnbextension
  - path.py
  - pycurl
  - wrapt
  - pyflakes
  - cookiecutter
  - ca-certificates
  - scipy
  - icc_rt
  - libdeflate
  - pyparsing
  - daal4py
  - soupsieve
  - conda-package-handling
  - lxml
  - ruamel_yaml
  - yapf
  - ptyprocess
  - importlib_metadata
  - pyrsistent
  - vs2015_runtime
  - sphinxcontrib-serializinghtml
  - sphinxcontrib
  - requests
  - dataclasses
  - zfp
  - libaec
  - atomicwrites
  - simplegeneric
  - krb5
  - blosc
  - argh
  - heapdict
  - qtpy
  - sphinxcontrib-jsmath
  - anaconda-navigator
  - cffi
  - openpyxl
  - isort
  - nose
  - jsonschema
  - h5py
  - vc
  - sphinxcontrib-qthelp
  - cloudpickle
  - winpty
  - mistune
  - sniffio
  - sqlalchemy
  - giflib
  - libiconv
  - pycosat
  - scikit-learn
  - pytz
  - debugpy
  - conda-token
  - hdf5
  - mccabe
  - imagesize
  - pandocfilters
  - partd
  - xlwt
  - freetype
  - beautifulsoup4
  - python-libarchive-c
  - xlrd
  - backports
  - notebook
  - arrow
  - intervaltree
  - astroid
  - docutils
  - m2w64-gcc-libs-core
  - libxml2
  - curl
  - pexpect
  - pycodestyle
  - clyent
  - matplotlib-base
  - mypy_extensions
  - alabaster
  - mkl_random
  - pywavelets
  - menuinst
  - colorama
  - pytest
  - regex
  - click
  - conda-content-trust
  - lcms2
  - bkcharts
  - pyls-spyder
  - statsmodels
  - imageio
  - patsy
  - py
  - backcall
  - sphinxcontrib-devhelp
  - cycler
  - bzip2
  - win_inet_pton
  - jupyter_client
  - typed-ast
  - olefile
  - binaryornot
  - matplotlib
  - numba
  - autopep8
  - dask
  - sqlite
  - ipywidgets
  - zipp
  - zstd
  - entrypoints
  - xz
  - zope.event
  - pathspec
  - python=3.9
  - blas
  - networkx
  - cfitsio
  - conda-verify
  - ipython_genutils
  - joblib
  - pytables
  - cryptography
  - fonttools
  - jupyter
  - pylint
  - cytoolz
  - keyring
  - jedi
  - liblief
  - qtawesome
  - ipykernel
  - bleach
  - pywin32
  - m2w64-libwinpthread-git
  - nltk
  - ply
  - pywin32-ctypes
  - psutil
  - libpng
  - pycparser
  - qtconsole
  - tinycss
  - prompt-toolkit
  - mpmath
  - jupyter_server
  - yaml
  - numpy
  - distributed
  - certifi
  - singledispatch
  - tifffile
  - contextlib2
  - comtypes
  - more-itertools
  - py-lief
  - fastcache
  - argon2-cffi
  - ipython
  - future
  - traitlets
  - snappy
  - chardet
  - get_terminal_size
  - gevent
  - m2w64-gcc-libs
  - pyyaml
  - testpath
  - pysocks
  - kiwisolver
  - libzopfli
  - intel-openmp
  - icu
  - toml
  - qstylizer
  - libtiff
  - xmltodict
  - numpy-base
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - libwebp
  - boto
  - tzdata
  - pyerfa
  - seaborn
  - jinja2
  - spyder-kernels
  - text-unidecode
  - libssh2
  - multipledispatch
  - six
  - backports.tempfile
  - msys2-conda-epoch
  - navigator-updater
  - brotli
  - scikit-learn-intelex
  - importlib-metadata
  - rope
  - conda-env
  - pygments
  - poyo
  - brotlipy
  - bcrypt
  - python-dateutil
  - xlwings
  - sphinxcontrib-applehelp
  - greenlet
  - sphinxcontrib-websupport
  - sphinxcontrib-htmlhelp
  - fsspec
  - flake8
  - defusedxml
  - openjpeg
  - json5
  - backports.weakref
  - werkzeug
  - conda-build
  - filelock
  - flask
  - conda-pack
  - three-merge
  - async_generator
  - webencodings
  - conda-repo-cli
  - libarchive
  - lerc
  - pyopenssl
  - pillow
  - python-lsp-black
  - zlib
  - charset-normalizer
  - mkl_fft
  - iniconfig
  - nest-asyncio
  - bokeh
  - numpydoc
  - libspatialindex
  - jupyter_contrib_nbextensions
  - pandoc
  - umap-learn
  - hdbscan
  - tabulate
  - levenshtein
  - pingouin
  - scikit-learn-extra
